import React from 'react';
import { SEOHead } from '../components/seo/SEOHead';
import { Breadcrumbs } from '../components/common/Breadcrumbs';
import { SITE_CONFIG } from '../config/site';

export const DisclaimerPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <SEOHead
        title="Disclaimer"
        description={`General disclaimer for ${SITE_CONFIG.name} online utilities.`}
        canonicalPath="/disclaimer"
      />

      <Breadcrumbs items={[{ label: 'Disclaimer' }]} />

      <div className="bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 rounded-3xl p-8 sm:p-12 shadow-sm space-y-6 text-slate-700 dark:text-slate-300 text-sm leading-relaxed">
        <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight mb-4">
          Disclaimer
        </h1>

        <p>
          The information and utilities provided by {SITE_CONFIG.name} ("we," "us," or "our") on our website are for general informational and productivity purposes only. All tools operate client-side in your browser.
        </p>

        <h2 className="text-lg font-bold text-slate-900 dark:text-white pt-2">No Professional Advice</h2>
        <p>
          The conversion, formatting, and mathematical outputs generated by our software should be verified independently before being relied upon for critical legal, financial, or engineering decisions.
        </p>

        <h2 className="text-lg font-bold text-slate-900 dark:text-white pt-2">External Links</h2>
        <p>
          Our website may contain links to external third-party websites. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites.
        </p>
      </div>
    </div>
  );
};
