import { ToolCategory, Tool, FAQItem } from '../types';

export const SITE_CONFIG = {
  name: 'Quick Toolo',
  fullName: 'Quick Toolo — Free Online Tools for Everyday Tasks',
  tagline: 'Quick Toolo — Free Online Tools for Everyday Tasks',
  description: 'Fast, simple, and free browser-based tools for images, PDFs, QR codes, text, and developers. No registration required, 100% private and secure.',
  defaultDomain: 'https://quicktoolo.netlify.app',
  author: 'Quick Toolo Platform',
};

export const CATEGORIES: ToolCategory[] = [
  {
    id: 'image',
    name: 'Image Tools',
    description: 'Compress, resize, and convert images instantly in your browser without quality loss.',
    iconName: 'Image',
    color: 'from-blue-500 to-blue-700',
    badgeBg: 'bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300',
  },
  {
    id: 'pdf',
    name: 'PDF Tools',
    description: 'Merge, compress, and convert images to PDF easily with maximum privacy.',
    iconName: 'FileText',
    color: 'from-rose-500 to-red-600',
    badgeBg: 'bg-rose-100 text-rose-800 dark:bg-rose-900/40 dark:text-rose-300',
  },
  {
    id: 'qr',
    name: 'QR Tools',
    description: 'Generate customizable, high-resolution QR codes for websites, WiFi, and contact cards.',
    iconName: 'QrCode',
    color: 'from-emerald-500 to-teal-600',
    badgeBg: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-300',
  },
  {
    id: 'text',
    name: 'Text Tools',
    description: 'Count words, analyze reading time, convert text cases, and calculate character limits.',
    iconName: 'AlignLeft',
    color: 'from-amber-500 to-orange-600',
    badgeBg: 'bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300',
  },
  {
    id: 'developer',
    name: 'Developer Tools',
    description: 'Format, validate, minify, and edit JSON data with line numbers and syntax diagnostics.',
    iconName: 'Code',
    color: 'from-purple-500 to-violet-600',
    badgeBg: 'bg-purple-100 text-purple-800 dark:bg-purple-900/40 dark:text-purple-300',
  },
];

export const TOOLS: Tool[] = [
  {
    id: 'qr-code-generator',
    title: 'QR Code Generator',
    h1: 'Free QR Code Generator',
    seoTitle: 'QR Code Generator – Create QR Codes Online | Quick Toolo',
    seoDescription: 'Create QR codes online for free with Quick Toolo. Generate QR codes quickly for links, text and other information.',
    slug: '/qr-code-generator',
    category: 'qr',
    popular: true,
    featured: true,
    shortDesc: 'Create customizable, high-resolution QR codes for URLs, text, WiFi credentials, or contact info.',
    longDesc: 'Generate custom QR codes instantly for free. Adjust colors, dimensions, and error correction levels, then download crisp PNG or SVG vector files ready for print or web usage.',
    iconName: 'QrCode',
    keywords: ['qr code generator', 'free qr code maker', 'custom qr code', 'create qr code png', 'url to qr code'],
    features: [
      '100% Free with no signup required',
      'Custom foreground and background color selection',
      'Adjustable pixel size up to 1024px',
      'Multiple Error Correction Levels (Low, Medium, Quartile, High)',
      'Instant PNG and vector download options',
      'Client-side generation for 100% privacy'
    ],
    howToSteps: [
      { step: 1, title: 'Enter Content', description: 'Paste a website URL, custom text message, or WiFi network detail into the input box.' },
      { step: 2, title: 'Customize Style', description: 'Choose your desired QR size, foreground color, background color, and error tolerance level.' },
      { step: 3, title: 'Download or Copy', description: 'Click the Download PNG button to save your generated QR code instantly to your device.' }
    ],
    faq: [
      { question: 'Do these QR codes expire?', answer: 'No! The QR codes generated by Quick Toolo are static QR codes that contain your exact data directly. They never expire and have no scan limits.' },
      { question: 'Is my input data kept private?', answer: 'Yes. All QR code calculations happen locally in your web browser. Nothing is sent to external servers.' },
      { question: 'Can I use these QR codes commercially?', answer: 'Yes, all generated QR codes are 100% free for commercial and personal printing, signage, and online use.' }
    ],
    relatedToolIds: ['word-character-counter', 'developer-tools', 'image-compressor']
  },
  {
    id: 'image-compressor',
    title: 'Image Compressor',
    h1: 'Free Image Compressor Online',
    seoTitle: 'Image Compressor – Compress Images Online | Quick Toolo',
    seoDescription: 'Compress images online for free with Quick Toolo. Reduce image file size while maintaining good image quality.',
    slug: '/image-compressor',
    category: 'image',
    popular: true,
    featured: true,
    shortDesc: 'Reduce image file size significantly while preserving visual quality in JPG, PNG, and WebP formats.',
    longDesc: 'Optimize your images for web performance and SEO. Lower file sizes by up to 80% without noticeable quality loss. Compare original vs compressed sizes in real time.',
    iconName: 'Minimize2',
    keywords: ['image compressor', 'compress jpg', 'compress png online', 'reduce image size', 'photo size reducer'],
    features: [
      'Batch process multiple image files simultaneously',
      'Interactive quality compression control slider',
      'Instant side-by-side file size reduction comparison',
      'Supports JPG, JPEG, PNG, and WebP input images',
      'Download individual compressed files or all in a single ZIP archive',
      'No file size restrictions or watermark added'
    ],
    howToSteps: [
      { step: 1, title: 'Upload Images', description: 'Drag and drop your image files or select them from your computer or mobile device.' },
      { step: 2, title: 'Adjust Compression', description: 'Move the quality slider to find your preferred balance between file size reduction and image clarity.' },
      { step: 3, title: 'Download Output', description: 'Click Download to get your optimized images instantly or download all in a ZIP file.' }
    ],
    faq: [
      { question: 'How much can image sizes be reduced?', answer: 'Depending on the original format and quality setting, you can typically shrink file sizes by 40% to 80% with zero visible loss.' },
      { question: 'Are my images stored on your servers?', answer: 'No. All image compression occurs directly inside your browser canvas. Your files never touch a cloud server.' },
      { question: 'What file formats are supported?', answer: 'We support JPG, JPEG, PNG, and WEBP image uploads.' }
    ],
    relatedToolIds: ['image-resizer', 'jpg-to-png', 'png-to-jpg', 'image-to-pdf']
  },
  {
    id: 'image-resizer',
    title: 'Image Resizer',
    h1: 'Free Image Resizer Online',
    seoTitle: 'Image Resizer – Resize Images Online | Quick Toolo',
    seoDescription: 'Resize images online for free with Quick Toolo. Change image width and height quickly and easily.',
    slug: '/image-resizer',
    category: 'image',
    popular: true,
    shortDesc: 'Resize photos and graphics by exact pixel dimensions or percentage ratios while maintaining aspect ratio.',
    longDesc: 'Quickly resize any picture for social media, websites, or email attachments. Lock the aspect ratio to prevent stretching, enter custom width and height (e.g. 600x500), and export crisp resized images.',
    iconName: 'Maximize2',
    keywords: ['image resizer', 'resize photo online', 'change image dimensions', 'pixel resizer', 'photo crop resize'],
    features: [
      'Custom pixel width and height inputs (fully editable & clearable)',
      'One-click aspect ratio locking',
      'Quick percentage presets (25%, 50%, 75%, 200%)',
      'High-quality canvas resampling algorithm',
      'Live image preview with updated dimension badge',
      'Export to PNG or JPG'
    ],
    howToSteps: [
      { step: 1, title: 'Select Image', description: 'Upload the photo or graphic you wish to resize.' },
      { step: 2, title: 'Set Dimensions', description: 'Enter target width and height in pixels (e.g. 600x500) or select a quick percentage preset.' },
      { step: 3, title: 'Download Resized', description: 'Preview the new dimensions and click Download Resized Image.' }
    ],
    faq: [
      { question: 'Will resizing stretch or distort my image?', answer: 'If you keep the "Lock Aspect Ratio" box checked, your image will resize proportionally without any distortion. You can also unlock aspect ratio for exact custom dimensions.' },
      { question: 'Can I increase the size of a small image?', answer: 'Yes, you can upscale images, though upscaling very small images may result in pixelation.' }
    ],
    relatedToolIds: ['image-compressor', 'jpg-to-png', 'png-to-jpg']
  },
  {
    id: 'image-to-pdf',
    title: 'Image to PDF Converter',
    h1: 'Image to PDF Converter',
    seoTitle: 'Image to PDF Converter – Convert Images to PDF | Quick Toolo',
    seoDescription: 'Convert images to PDF online for free with Quick Toolo. Quickly turn your images into PDF files.',
    slug: '/image-to-pdf',
    category: 'pdf',
    popular: true,
    featured: true,
    shortDesc: 'Convert JPG, PNG, and WebP images into a clean, single PDF document with custom margins.',
    longDesc: 'Turn multiple photos, scans, and graphic files into a professional PDF document. Reorder pages, set page orientation (portrait/landscape), adjust margins, and export in seconds.',
    iconName: 'FileSpreadsheet',
    keywords: ['image to pdf', 'convert jpg to pdf', 'png to pdf maker', 'photos to pdf', 'combine pictures into pdf'],
    features: [
      'Combine unlimited images into a single clean PDF file',
      'Drag-and-drop page reordering controls',
      'Page Orientation options: Auto, Portrait, Landscape',
      'Margin settings: No Margin, Small, Medium',
      'Supports JPG, PNG, WEBP, and BMP formats',
      'Fast client-side PDF creation using PDF-Lib'
    ],
    howToSteps: [
      { step: 1, title: 'Upload Images', description: 'Add all images you want to include in your PDF document.' },
      { step: 2, title: 'Arrange & Configure', description: 'Drag images up or down to set page order, and choose orientation or margin settings.' },
      { step: 3, title: 'Create PDF', description: 'Click Convert to PDF to generate and download your new PDF document.' }
    ],
    faq: [
      { question: 'Can I reorder pages before generating the PDF?', answer: 'Yes, you can easily drag and drop or use arrow buttons to arrange your images in any sequence.' },
      { question: 'Are there limits on how many images I can convert?', answer: 'No, you can combine as many images as you need into a single PDF document.' }
    ],
    relatedToolIds: ['pdf-merger', 'pdf-compressor', 'image-compressor']
  },
  {
    id: 'pdf-merger',
    title: 'PDF Merger',
    h1: 'Merge PDF Files Online',
    seoTitle: 'PDF Merger – Merge PDF Files Online | Quick Toolo',
    seoDescription: 'Merge multiple PDF files into one document online for free with Quick Toolo.',
    slug: '/pdf-merger',
    category: 'pdf',
    popular: true,
    featured: true,
    shortDesc: 'Combine multiple PDF files into one organized PDF document effortlessly in your browser.',
    longDesc: 'Merge multiple PDF files into a single consolidated PDF document. No file uploads to cloud servers means total security for sensitive business, legal, and personal documents.',
    iconName: 'Layers',
    keywords: ['pdf merger', 'combine pdf files', 'merge pdf online', 'join pdf documents', 'free pdf binder'],
    features: [
      'Combine multiple PDF documents into a single file',
      'Reorder PDFs before merging',
      'Live total page count display',
      '100% Client-side processing using WebAssembly and PDF-Lib',
      'Fast merging speed with zero server bandwidth delay',
      'No document watermarks added'
    ],
    howToSteps: [
      { step: 1, title: 'Select PDF Files', description: 'Choose two or more PDF documents from your file browser or drag them into the box.' },
      { step: 2, title: 'Reorder List', description: 'Use the move up and move down controls to position files in your preferred order.' },
      { step: 3, title: 'Merge & Download', description: 'Click Merge PDFs to combine all documents and download the final PDF instantly.' }
    ],
    faq: [
      { question: 'Are my PDF documents uploaded to a server?', answer: 'No! All merging is performed directly in your web browser memory using JavaScript. Your confidential files never leave your computer.' },
      { question: 'Is there a limit on how many PDF files I can merge?', answer: 'There are no strict software limits. You can merge as many PDF files as your device memory allows.' }
    ],
    relatedToolIds: ['pdf-compressor', 'image-to-pdf', 'word-character-counter']
  },
  {
    id: 'word-character-counter',
    title: 'Word & Character Counter',
    h1: 'Word & Character Counter',
    seoTitle: 'Word and Character Counter – Count Words Online | Quick Toolo',
    seoDescription: 'Count words and characters online for free with Quick Toolo. Get quick and accurate text statistics.',
    slug: '/word-character-counter',
    aliases: ['/word-counter', 'word-counter', 'word-character-counter'],
    category: 'text',
    popular: true,
    shortDesc: 'Count words, characters, sentences, paragraphs, and calculate reading/speaking time in real time.',
    longDesc: 'Free online word count tool for essays, social media posts, blogs, and copywriting limits. Includes keyword density frequency stats and one-click text case converters.',
    iconName: 'Type',
    keywords: ['word counter', 'character count tool', 'online word count', 'sentence counter', 'text case converter', 'word character counter'],
    features: [
      'Real-time calculation as you type or paste text',
      'Detailed metric breakdown: Words, Chars (with spaces), Chars (no spaces), Sentences, Paragraphs',
      'Estimated Reading Time (200 wpm) & Speaking Time (130 wpm)',
      'Top keyword frequency density analysis table',
      'Text Case Converter: UPPERCASE, lowercase, Title Case, Sentence case',
      'One-click Copy & Clear controls'
    ],
    howToSteps: [
      { step: 1, title: 'Type or Paste Text', description: 'Paste your article, essay, social post, or code into the text editor box.' },
      { step: 2, title: 'View Real-Time Metrics', description: 'Instantly inspect total words, character count limits, reading time, and top keywords.' },
      { step: 3, title: 'Convert or Copy', description: 'Use the text transformation utilities to alter letter casing, then copy your refined text.' }
    ],
    faq: [
      { question: 'How is reading time calculated?', answer: 'Reading time is calculated using the industry standard average speed of 200 words per minute for adult readers.' },
      { question: 'Is there a limit on how much text I can paste?', answer: 'No, you can paste large documents, articles, or manuscripts without performance lag.' }
    ],
    relatedToolIds: ['developer-tools', 'qr-code-generator']
  },
  {
    id: 'jpg-to-png',
    title: 'JPG to PNG Converter',
    h1: 'JPG to PNG Converter',
    seoTitle: 'JPG to PNG Converter – Convert JPG to PNG Online | Quick Toolo',
    seoDescription: 'Convert JPG images to PNG format online for free with Quick Toolo.',
    slug: '/jpg-to-png',
    category: 'image',
    popular: false,
    shortDesc: 'Convert JPG or JPEG images to transparent PNG format quickly and cleanly.',
    longDesc: 'Transform JPG images into lossless PNG format instantly. Ideal for graphic designers, webmasters, and publishing workflows needing high-quality PNG outputs.',
    iconName: 'ArrowRightLeft',
    keywords: ['jpg to png', 'convert jpg to png', 'jpeg to png converter', 'free image converter', 'save jpg as png'],
    features: [
      'Lossless conversion from JPG/JPEG to PNG',
      'Batch conversion support for multiple photos',
      'Preserves maximum color accuracy and sharpness',
      'Instant live preview before saving',
      'Download individual PNG files or all as a ZIP archive'
    ],
    howToSteps: [
      { step: 1, title: 'Upload JPGs', description: 'Select one or multiple JPG or JPEG files from your device.' },
      { step: 2, title: 'Review Preview', description: 'Our browser converter automatically processes your images into crisp PNG format.' },
      { step: 3, title: 'Download PNGs', description: 'Save your newly converted PNG images to your computer or phone.' }
    ],
    faq: [
      { question: 'Why convert JPG to PNG?', answer: 'PNG files use lossless compression, making them better suited for graphics, text screenshots, and crisp printing.' },
      { question: 'Is this converter free?', answer: 'Yes, 100% free with unlimited conversions and no registration.' }
    ],
    relatedToolIds: ['png-to-jpg', 'image-compressor', 'image-to-pdf']
  },
  {
    id: 'png-to-jpg',
    title: 'PNG to JPG Converter',
    h1: 'PNG to JPG Converter',
    seoTitle: 'PNG to JPG Converter – Convert PNG to JPG Online | Quick Toolo',
    seoDescription: 'Convert PNG images to JPG format online for free with Quick Toolo.',
    slug: '/png-to-jpg',
    category: 'image',
    popular: false,
    shortDesc: 'Convert PNG images to lightweight JPG format with customizable background color filling.',
    longDesc: 'Convert heavy PNG images to compact JPG files. Choose your preferred background fill color for transparent PNGs and select JPG quality settings.',
    iconName: 'ArrowRightLeft',
    keywords: ['png to jpg', 'convert png to jpg', 'png to jpeg online', 'transparent png to jpg', 'shrink png to jpg'],
    features: [
      'Custom background color selector for transparent PNGs (White, Black, or Custom)',
      'Adjustable JPG compression quality slider',
      'Batch conversion of multiple files',
      'Real-time before/after preview',
      'Significantly smaller file size output'
    ],
    howToSteps: [
      { step: 1, title: 'Select PNG Files', description: 'Upload your PNG graphics or transparent screenshots.' },
      { step: 2, title: 'Choose Background Color', description: 'Select white or a custom background color to fill any transparent regions.' },
      { step: 3, title: 'Download JPGs', description: 'Click Download to save your lightweight JPG files.' }
    ],
    faq: [
      { question: 'What happens to transparent areas in my PNG?', answer: 'Since JPG does not support transparency, transparent areas will be filled with the solid background color you choose (default is clean white).' },
      { question: 'Does converting reduce file size?', answer: 'Yes, converting complex PNG photos to JPG almost always reduces file size substantially.' }
    ],
    relatedToolIds: ['jpg-to-png', 'image-compressor', 'image-resizer']
  },
  {
    id: 'pdf-compressor',
    title: 'PDF Compressor',
    h1: 'Free PDF Compressor Online',
    seoTitle: 'PDF Compressor – Compress PDF Files Online | Quick Toolo',
    seoDescription: 'Compress PDF files online for free with Quick Toolo. Reduce PDF file size quickly and easily.',
    slug: '/pdf-compressor',
    category: 'pdf',
    popular: false,
    shortDesc: 'Reduce PDF file size for easier emailing and uploading while preserving document structure.',
    longDesc: 'Shrink oversized PDF files quickly. Optimize PDF streams, remove redundant embedded object structures, and reduce document footprint without compromising content accuracy.',
    iconName: 'FileArchive',
    keywords: ['pdf compressor', 'compress pdf online', 'shrink pdf size', 'reduce pdf file size', 'pdf optimizer'],
    features: [
      'Smart PDF stream optimization',
      'Multiple compression levels: Recommended, Maximum, Light',
      'Clear calculation showing original size, compressed size, and savings percentage',
      'Preserves links, text selectable streams, and fonts',
      '100% Private local browser execution'
    ],
    howToSteps: [
      { step: 1, title: 'Upload PDF', description: 'Drag and drop your large PDF file into the compressor.' },
      { step: 2, title: 'Choose Preset', description: 'Select your target compression level.' },
      { step: 3, title: 'Compress & Save', description: 'Click Compress PDF and download your smaller file size PDF.' }
    ],
    faq: [
      { question: 'Will text remain crisp and searchable?', answer: 'Yes! Our compression optimizes internal document data structures while keeping vector text sharp and selectable.' },
      { question: 'Is my document safe?', answer: 'Yes. Processing is strictly browser-based so your PDF content remains completely confidential.' }
    ],
    relatedToolIds: ['pdf-merger', 'image-to-pdf', 'image-compressor']
  },
  {
    id: 'developer-tools',
    title: 'Developer Tools',
    h1: 'Free Online Developer Tools',
    seoTitle: 'Developer Tools – Free Online Developer Tools | Quick Toolo',
    seoDescription: 'Use free online developer tools from Quick Toolo for common coding and development tasks.',
    slug: '/developer-tools',
    aliases: ['/json-formatter', 'json-formatter', 'developer-tools'],
    category: 'developer',
    popular: true,
    featured: true,
    shortDesc: 'Format, validate, beautify, and minify JSON data with instant syntax error detection.',
    longDesc: 'Clean up and validate JSON code with our browser-based developer utility. Beautify with custom indentation (2 or 4 spaces), minify for lightweight production payloads, detect syntax issues, and export formatted code.',
    iconName: 'Code',
    keywords: ['developer tools', 'json formatter', 'json validator', 'beautify json', 'json minifier', 'json parser online', 'json syntax checker'],
    features: [
      'Beautify JSON with 2-space, 4-space, or Tab indentation',
      'Minify JSON to single-line compact format',
      'Instant validation with precise error line & column feedback',
      'Load sample JSON data for quick testing',
      'One-click Copy to Clipboard and Download .json file',
      'Cleans escaped quotes and handles complex nested objects'
    ],
    howToSteps: [
      { step: 1, title: 'Paste JSON Data', description: 'Paste raw, minified, or unformatted JSON into the editor input area.' },
      { step: 2, title: 'Format or Minify', description: 'Click Format JSON to beautify structure or Minify to condense into a lightweight string.' },
      { step: 3, title: 'Validate & Copy', description: 'Verify error-free syntax and click Copy to Clipboard or Download file.' }
    ],
    faq: [
      { question: 'What developer utilities are included?', answer: 'Quick Toolo Developer Tools currently includes a high-performance JSON Formatter, Minifier, Validator, Syntax Error Detector, and JSON Exporter, running 100% locally in your browser.' },
      { question: 'What happens if my JSON is invalid?', answer: 'The tool highlights syntax errors and gives you clear diagnostic information indicating the line and character where parsing failed.' },
      { question: 'Is my confidential code and JSON data safe?', answer: 'Yes. All parsing and formatting operations occur exclusively inside your web browser. No API tokens, JSON payloads, or code snippets are transmitted over any network.' }
    ],
    relatedToolIds: ['word-character-counter', 'qr-code-generator']
  }
];

export const GENERAL_FAQS: FAQItem[] = [
  {
    question: 'Are all tools on Quick Toolo completely free to use?',
    answer: 'Yes! Every single tool on Quick Toolo is 100% free with unlimited usage. You do not need to register an account, enter credit card details, or install any software.'
  },
  {
    question: 'Are my files and personal data secure?',
    answer: 'Absolutely. All processing occurs 100% client-side inside your own web browser using modern WebAssembly and Canvas JavaScript APIs. Your documents, photos, and text are never uploaded to cloud servers.'
  },
  {
    question: 'Can I use these tools on my mobile phone or tablet?',
    answer: 'Yes! Quick Toolo is fully responsive and mobile-optimized to work seamlessly across iPhones, Android devices, iPads, tablets, laptops, and desktop computers.'
  },
  {
    question: 'How do I suggest a new tool or report an issue?',
    answer: 'We welcome user suggestions! Visit our Contact page to send feature requests, new tool ideas, or bug reports directly to our development team.'
  }
];

